# Generated by Django 4.2.18 on 2025-02-02 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TikTokUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TikTokVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.BigIntegerField(unique=True)),
                ('video_description', models.TextField()),
                ('create_time', models.DateTimeField()),
                ('comment_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('share_count', models.IntegerField()),
                ('view_count', models.IntegerField()),
                ('music_id', models.BigIntegerField()),
                ('region_code', models.CharField(max_length=255)),
                ('hashtags', models.ManyToManyField(blank=True, related_name='tt_videos', to='scraper.hashtag')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraper.tiktokuser')),
            ],
        ),
    ]
