# Generated by Django 4.2.18 on 2025-02-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokvideo',
            name='video_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
