# Generated by Django 4.2.18 on 2025-02-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_tiktokvideo_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokvideo',
            name='hashtags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tt_videos', to='scraper.hashtag'),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='music_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
