# Generated by Django 4.2.18 on 2025-02-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_tiktokvideo_hashtags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokvideo',
            name='comment_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='tt_videos', to='scraper.hashtag'),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='like_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='region_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='share_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='view_count',
            field=models.IntegerField(null=True),
        ),
    ]
