# Generated by Django 4.2.18 on 2025-02-06 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_alter_tiktokvideo_comment_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokvideo',
            name='scrape_date',
            field=models.DateTimeField(default=datetime.datetime(1999, 12, 31, 23, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
