# Generated by Django 4.2.19 on 2025-03-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0007_remove_hashtag_author_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tiktokvideo_b",
            name="channel_tags",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="tiktokvideo_b",
            name="comments",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="tiktokvideo_b",
            name="diversification_labels",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="tiktokvideo_b",
            name="effect_stickers",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="tiktokvideo_b",
            name="keyword_tags",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="tiktokvideo_b",
            name="mentions",
            field=models.ManyToManyField(
                blank=True, related_name="mentions_b", to="scraper.tiktokuser"
            ),
        ),
        migrations.AlterField(
            model_name="tiktokvideo_b",
            name="stickers_on_item",
            field=models.JSONField(null=True),
        ),
    ]
