# Generated by Django 4.2.19 on 2025-03-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0008_alter_tiktokvideo_b_channel_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tiktokvideo_b",
            name="create_time",
            field=models.DateTimeField(null=True),
        ),
    ]
