# Generated by Django 4.2.19 on 2025-03-06 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0009_alter_tiktokvideo_b_create_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="TikTokUser_B",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("author_id", models.BigIntegerField(null=True, unique=True)),
                ("nick_name", models.CharField(max_length=255, null=True)),
                ("signature", models.TextField(null=True)),
                ("create_time", models.IntegerField(null=True)),
                ("verified", models.BooleanField(default=False)),
                ("ftc", models.BooleanField(default=False)),
                ("relation", models.IntegerField(null=True)),
                ("open_favorite", models.BooleanField(default=False)),
                ("comment_setting", models.IntegerField(null=True)),
                ("duet_setting", models.SmallIntegerField(null=True)),
                ("stitch_setting", models.SmallIntegerField(null=True)),
                ("private_account", models.BooleanField(default=False)),
                ("secret", models.BooleanField(default=False)),
                ("is_ad_virtual", models.BooleanField(default=False)),
                ("download_setting", models.SmallIntegerField(null=True)),
                ("recommend_reason", models.CharField(max_length=255, null=True)),
                ("suggest_account_bind", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="tiktokuser",
            name="author_id",
        ),
        migrations.RemoveField(
            model_name="tiktokuser",
            name="comment_setting",
        ),
        migrations.RemoveField(
            model_name="tiktokuser",
            name="create_time",
        ),
        migrations.RemoveField(
            model_name="tiktokuser",
            name="download_setting",
        ),
        migrations.RemoveField(
            model_name="tiktokuser",
            name="duet_setting",
        ),
        migrations.RemoveField(
            model_name="tiktokuser",
            name="ftc",
        ),
        migrations.RemoveField(
            model_name="tiktokuser",
            name="is_ad_virtual",
        ),
        migrations.RemoveField(
            model_name="tiktokuser",
            name="nick_name",
        ),
        migrations.RemoveField(
            model_name="tiktokuser",
            name="open_favorite",
        ),
        migrations.RemoveField(
            model_name="tiktokuser",
            name="private_account",
        ),
        migrations.RemoveField(
            model_name="tiktokuser",
            name="recommend_reason",
        ),
        migrations.RemoveField(
            model_name="tiktokuser",
            name="relation",
        ),
        migrations.RemoveField(
            model_name="tiktokuser",
            name="secret",
        ),
        migrations.RemoveField(
            model_name="tiktokuser",
            name="signature",
        ),
        migrations.RemoveField(
            model_name="tiktokuser",
            name="stitch_setting",
        ),
        migrations.RemoveField(
            model_name="tiktokuser",
            name="suggest_account_bind",
        ),
        migrations.RemoveField(
            model_name="tiktokuser",
            name="verified",
        ),
        migrations.RemoveField(
            model_name="tiktokvideo_b",
            name="username",
        ),
        migrations.AlterField(
            model_name="tiktokuser",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tiktokvideo_b",
            name="scrape_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="tiktokvideo_b",
            name="author_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scraper.tiktokuser_b",
            ),
        ),
        migrations.AlterField(
            model_name="tiktokvideo_b",
            name="mentions",
            field=models.ManyToManyField(
                blank=True, related_name="mentions_b", to="scraper.tiktokuser_b"
            ),
        ),
    ]
