# Generated by Django 4.2.19 on 2025-03-06 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0010_tiktokuser_b_remove_tiktokuser_author_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tiktokvideo",
            old_name="username",
            new_name="author_id",
        ),
    ]
