# Generated by Django 4.2.19 on 2025-03-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0011_rename_username_tiktokvideo_author_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tiktokvideo_b",
            name="enable_audio_caption",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="tiktokvideo_b",
            name="has_original_audio",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
