# Generated by Django 4.2.18 on 2025-03-07 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_alter_tiktokvideo_b_enable_audio_caption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiktokuser_b',
            options={'verbose_name': 'TikTok User (scraper B)', 'verbose_name_plural': 'TikTok Users (scraper B)'},
        ),
        migrations.AlterModelOptions(
            name='tiktokvideo_b',
            options={'verbose_name': 'TikTok Video (scraper B)', 'verbose_name_plural': 'TikTok Videos (scraper B)'},
        ),
        migrations.AlterField(
            model_name='tiktokuser_b',
            name='author_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tiktokuser_b',
            name='comment_setting',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokuser_b',
            name='create_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokuser_b',
            name='download_setting',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokuser_b',
            name='duet_setting',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokuser_b',
            name='nick_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokuser_b',
            name='recommend_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokuser_b',
            name='relation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokuser_b',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokuser_b',
            name='stitch_setting',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='ai_gc_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='author_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraper.tiktokuser_b'),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='channel_tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='collectcount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='comment_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='comments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='diggcount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='diversification_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='diversification_labels',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='duet_display',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='effect_stickers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='enable_audio_caption',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='filepath',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='has_original_audio',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='item_comment_status',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='keyword_tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='like_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='music_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='no_caption_reason',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='poi_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='poi_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='poi_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='ratio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='region_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='repostcount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='schedule_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='share_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='stickers_on_item',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='stitch_display',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='suggested_words',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='take_down',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='video_id',
            field=models.DecimalField(decimal_places=0, max_digits=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='view_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='volume_loudness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='volume_peak',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='warn_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
