# Generated by Django 4.2.18 on 2025-03-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0014_tiktokuser_b_date_added_tiktokuser_b_scrape_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokuser_b',
            name='author_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='video_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
