# Generated by Django 4.2.18 on 2025-03-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0015_alter_tiktokuser_b_author_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokvideo_b',
            name='scrape_priority',
            field=models.IntegerField(default=0),
        ),
    ]
