# Generated by Django 4.2.18 on 2025-03-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0016_tiktokvideo_b_scrape_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokvideo_b',
            name='content_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
