# Generated by Django 4.2.18 on 2025-03-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0017_tiktokvideo_b_content_downloaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokvideo_b',
            name='suggested_words',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
