name: Test Dev

on:
  push:
    branches: [ dev ]

jobs:
  build:
    if: false
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          MYSQL_DATABASE: ddmtestdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      env:
        DJANGO_SECRET: ${{ secrets.DJANGO_SECRET }}
        DJANGO_SETTINGS_MODULE: config.settings.production
        DJANGO_DB_NAME: ddmtestdb
        DJANGO_DB_USER: root
        DJANGO_DB_PW: password
        DJANGO_DB_HOST: 127.0.0.1
      run: |
        python manage.py migrate
        python manage.py collectstatic
    - name: Run Tests
      env:
        DJANGO_SECRET: ${{ secrets.DJANGO_SECRET }}
        DJANGO_SETTINGS_MODULE: config.settings.production
        DJANGO_DB_NAME: ddmtestdb
        DJANGO_DB_USER: root
        DJANGO_DB_PW: password
        DJANGO_DB_HOST: 127.0.0.1
      run: |
        python manage.py test
